### ISSUE TITLE
RemoteCommand not parsed

### ISSUE THREAD

**Issue by sonnius** [moul/assh#286]
Hello,

I've noticed that RemoteComand is not parsed by assh, looking through the source code it's not currently in the list: advanced-ssh-config/pkg/config/host.go

Is this by design or Is this simply missing?

Thanks,
Rob

**Comment by lcrockett** [comment]
Any news on this ? I am also wondering about the absence of the 'RemoteCommand' OpenSSH configuration option.

**Comment by moul** [comment]
Hi, thank you for your feedback, I think this was fixed in a previous PR, please reopen and add more details if you think it needs more work.

**Comment by lcrockett** [comment]
Thank you for the feedback. I was unable to find a pre-existing PR for the specified functionality, therefore i've just created one, see https://github.com/moul/assh/pull/349

Once this change has propagated to the Homebrew version of `assh` i'll be able to test it out.
