### ISSUE TITLE
Release a new version from master?

### ISSUE THREAD

**Issue by wd** [moul/assh#330]
Since the v2.8.0 was released on Jul 4, 2018, would you mind to release a new version? I think there's lots bug fixed.

**Comment by wd** [comment]
I have tried to install use `brew install assh --head` but failed with error 
`go: github.com/StackExchange/wmi@v0.0.0-20190530172153-cbe66965904d: invalid pseudo-version: does not match version-control timestamp (2019-05-23T21:33:15Z)`

I don't know how to fix it.

**Comment by moul** [comment]
Hi @wd, I just made a release of master using a new method

I didn't try to run it on Mac OS for now, can you try a new `brew install assh --head` and tell me if it works? If not I will give a try soon on a mac :)

**Comment by moul** [comment]
Closing the issue as I plan to work on the v3 of this project and I need to make some cleanup in the issues see #334 

And do not hesitate to reopen this issue if necessary

**Comment by wd** [comment]
Thanks, after edit the assh.rb shipped by  homebrew, I can install from head now. I'll give them a PR to fix it.

```
$ assh --version                                                                                                                                                               assh version 2.8.0+dev (HEAD) 
```
Is the version number correct?
