### ISSUE TITLE
Can't resolve hostname during initialization

### ISSUE THREAD

**Issue by shadowrylander** [moul/assh#331]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; I seem to be getting the following after running `assh -i 127.0.0.1 22`:
```bash
ASSH -- The Anonymous Secure SHell (Version 2.3)
[+] Initialisation from url (http://www.proxy-list.net/anonymous-proxy-lists.shtml)
[-] Cant resolve hostname
```
&nbsp;&nbsp;&nbsp;&nbsp; My `assh.yml` is in `~/.ssh/`, with the corrent permissions on the directory; is there anything I'm missing?
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for the help!

&nbsp;&nbsp;&nbsp;&nbsp; `P.S. :` How do I use the [`Eternal Terminal`](https://eternalterminal.dev/) with this, considering setting `Mosh` up with `ProxyCommand` is quite a bit trickier?

**Comment by moul** [comment]
Hi @shadowrylander,

`ASSH -- The Anonymous Secure SHell (Version 2.3)` is not the same as https://github.com/moul/assh

First, you need to only keep one binary with the name `assh` or configure your system to explicitly call the one you want

As soon as your system is well configured, every software using the `libssh` (most of the softwares using SSH actually) will go through `assh`

**Comment by shadowrylander** [comment]
Oof... I walked right into that. My sincerest apologies for wasting your time! 😅😅😅😅
