### ISSUE TITLE
Unable to build latest version using GO

### ISSUE THREAD

**Issue by e3eli3h** [moul/assh#336]
Hello,

```
$ go get -u -v moul.io/assh/v2
Fetching https://moul.io/assh/v2?go-get=1
Parsing meta tags from https://moul.io/assh/v2?go-get=1 (status code 200)
get "moul.io/assh/v2": found meta tag get.metaImport{Prefix:"moul.io/assh", VCS:"git", RepoRoot:"https://github.com/moul/assh"} at https://moul.io/assh/v2?go-get=1
get "moul.io/assh/v2": verifying non-authoritative meta tag
Fetching https://moul.io/assh?go-get=1
Parsing meta tags from https://moul.io/assh?go-get=1 (status code 200)
moul.io/assh (download)
package moul.io/assh/v2: cannot find package "moul.io/assh/v2" in any of:
	/usr/local/go/src/moul.io/assh/v2 (from $GOROOT)
	/home/e3eli3h/go/src/moul.io/assh/v2 (from $GOPATH)
```

Am I doing something wrong?

**Comment by jycamier** [comment]
Same problem

**Comment by moul** [comment]
:wave: thank you for this report

Which version of GO are you using? What's your current value for the `$GO111MODULE` env var?

**Comment by moul** [comment]
fyi, I just uploaded binaries for each supported platforms on the release: https://github.com/moul/assh/releases/tag/v2.9.1

**Comment by jycamier** [comment]
> Which version of GO are you using? What's your current value for the $GO111MODULE env var?

Empty. I didn't know this one.

```shell
env GO111MODULE=on go get -u -v moul.io/assh/v2 
```
With it, it workds.

**Comment by moul** [comment]
:+1:

Thank you, this kind of bug is always a nightmare to manage; if someone has an idea to avoid this kind of error? or an idea of build instructions to add in the README, feel free to comment, thx!
