### ISSUE TITLE
Github release assets missing since 2.9.1

### ISSUE THREAD

**Issue by frezbo** [moul/assh#386]
After 2.9.1 the only released assets are the source code zip/tar. Did something change?

**Comment by frezbo** [comment]
@moul something in CI changed? The README still mentions to download from github releases

**Comment by moul** [comment]
:wave:,

I just fixed it and hope it will also be fixed for the next releases :)

Thank you for this issue :+1:

-> https://github.com/moul/assh/releases/tag/v2.11.0

**Comment by frezbo** [comment]
@moul Thanks a lot :heart:

**Comment by frezbo** [comment]
@moul The releases seems to be missing for the v2.12.0 too
