### ISSUE TITLE
Fails to build on macOS

### ISSUE THREAD

**Issue by austinbutler** [moul/assh#476]
Cause looks to be https://github.com/shirou/gopsutil/issues/976.

I see the bot already had opened a PR to upgrade `gopsutil` with https://github.com/moul/assh/pull/467 but @moul you closed that. Not sure what the plan is so opening this to make you aware of the impact.

**Comment by moul** [comment]
yes, that’s because the dependency bot tried to upgrade a major version of a golang dependency (v2 -> v3)which requires updating the import path in the .go files, so I closed it since it can only break everything

I’ll make the bump manually to ensure everything works correctly

**Comment by moul** [comment]
Hum, finally the automated PR should have been good since gopsutil is not using go mod :)
